<?php

namespace AppBundle\Repository;

/**
 * TaskReferentialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskReferentialRepository extends \Doctrine\ORM\EntityRepository
{
}
